# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: wk
    description: "Git worktree helper with hooks support"
    homepage: "https://github.com/lucas-stellet/wk"
    license: "MIT"
    repository:
      owner: lucas-stellet
      name: homebrew-wk
    directory: Formula
    commit_author:
      name: lucas-stellet
      email: lustepe@gmail.com
    install: |
      bin.install "wk"
    test: |
      system "#{bin}/wk", "--help"
